/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XwireGrid {
    }
}
declare global {
    interface HTMLXwireGridElement extends Components.XwireGrid, HTMLStencilElement {
    }
    var HTMLXwireGridElement: {
        prototype: HTMLXwireGridElement;
        new (): HTMLXwireGridElement;
    };
    interface HTMLElementTagNameMap {
        "xwire-grid": HTMLXwireGridElement;
    }
}
declare namespace LocalJSX {
    interface XwireGrid {
    }
    interface IntrinsicElements {
        "xwire-grid": XwireGrid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xwire-grid": LocalJSX.XwireGrid & JSXBase.HTMLAttributes<HTMLXwireGridElement>;
        }
    }
}
